### ISSUE TITLE
what is the meaning of this code?

### ISSUE THREAD

**Issue by policeme** [Kyubyong/transformer#102]
@Kyubyong 
![image](https://user-images.githubusercontent.com/30991932/55936331-8dfc7f00-5c68-11e9-97b8-ecf95e3a9d6c.png)

**Comment by policeme** [comment]
the shape of y_hat is [batch _size, 1], so tf.reduce_sum's result will be [batch_size], but the self.token2idx is a number, list can equal to number?

**Comment by ty5491003** [comment]
Delete it and the result changed nothing. I think it is a "residual" code.

**Comment by DMIRICA** [comment]
That if will break the for loop when the last prediction of all items from a batch is equal to the index of <pad> which is 0. This will save useless iterations. As you know the outputs have different lengths, so you don't know exactly how many times to iterate until you get the output for all items.
Hope you understood.

**Comment by policeme** [comment]
@DMIRICA but tf.reduce_sum(y_hat,1) is still a list, and self.token2idx["<pad>"] is a number, Is list equal to number?

**Comment by DMIRICA** [comment]
Yeah, my mistake, I think it should be something like tf.reduce_sum(y_hat, 0)[-1]

**Comment by BonjourDeutsch** [comment]
I also think it should be something like tf.reduce_sum(y_hat, 0)[-1]. Perfect!
