### ISSUE TITLE
An easy question about linear

### ISSUE THREAD

**Issue by guotong1988** [Kyubyong/transformer#4]
https://github.com/Kyubyong/transformer/blob/master/modules.py#L150-L153
Why use relu? 
Is it that linear means no relu or no sigmoid?
@Kyubyong thank you thank you

**Comment by Kyubyong** [comment]
Right. But the paper didn't clarify if they applied nonlinear activation after the linear transformation. Actually, I tested without the relu part, and the training didn't work. You can try it.
